language: node_js
node_js:
  - "14"

services:
  - docker

before_install:
  - curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
  - sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
  - sudo apt-get update && sudo apt-get install terraform

install:
  - npm install

before_script:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - az account set --subscription $AZURE_SUBSCRIPTION_ID

script:
  - npm test
  - docker-compose build
  - docker-compose push
  - kubectl apply -f ba-deployment-munleng.yaml
  - kubectl apply -f ba-service-munleng.yaml
  - kubectl rollout history deployment/ba-deployment
  - kubectl get pods
  - kubectl get services
  - cd ba-terraform
  - terraform init
  - terraform plan
  - echo "yes" | terraform apply
