trigger:
- main

pool:
  vmImage: ubuntu-latest

jobs:
- job: Test
  displayName: 'Run Tests'
  steps:
  - checkout: self

  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install Node.js'

  - script: |
      rm -rf ./BrainAcademy2.0/node_modules/*
      cd ./BrainAcademy2.0
      npm install
      npm test
    displayName: 'Install dependencies and run tests'
